### ISSUE TITLE
SRF08 is restrained to 1m

### ISSUE THREAD

**Issue by LeoColomb** [LeoColomb/Arduino-SRF#4]
The library need to be aware of gain and location to add a delay between ping and and listener.
- Let the sensor get the length
- Avoid echo error

**Comment by hariadi04** [comment]
hey can u help me,.??  i juts got error

"Sensor SRF08 not detected"

i folow this 
http://playground.arduino.cc/Main/SonarSrf08 and try https://github.com/LeoColomb/Arduino-SRF/releases/tag/v2.3-RC
