### ISSUE TITLE
Unable to connect with sensor

### ISSUE THREAD

**Issue by AhUhmm** [LeoColomb/Arduino-SRF#7]
I have tried to use this library with a SRF08, and tested the corresponding example, but I don't even get the "Sensor X not connected..." message on the serial monitor.

Am I missing something?

I checked the I2C address of my sensor and then changed it on the code but nothing happens.

**Comment by LeoColomb** [comment]
Thanks for your post!
That said your report miss a lot of information needed to define your specific case:
* Which Arduino board do you use?
* What versions of all software & hardware involved?
* How is the compilation?
* Did you tried the example? Output?

This list of basic question is *not* exhaustive, you may add any other detail to help us understand your situation.

**Comment by AhUhmm** [comment]
Yeah, you are right!

First of all thank yoou for your quick reply!

I'll try to be as thorough as possible:
I'm using an Arduino UNO R3 with the latest IDE, all the libraries up to date, including Wire (v.1.0.0). As for the hardware I'm using an SRF08, but I can't provide many more informations about it cause I don't have any datasheet.

I use the AVRISP mkII, and I don't get any error while compiling the example SRF08 included in your library, but on the first try I didn't get any output at all.

I then modified the code of SRF08 example at line 15 and deleted the bitshift operand. That way on the Serial monitor I get the "Sensor SRF08 connected (11)", but no sensor reading, like this:

`#define MAIN_08_ADDRESS 0x7C`

I wanted to try your library in the first place because I cannot get readings over 1,5 meters, but I need a 6 meters range.

**Comment by LeoColomb** [comment]
> and deleted the bitshift operand

Hmm, OK, why not.

> I get the "Sensor SRF08 connected (11)"

Ah! Good! LEDs on the sensor are blinking (at least once)?
Then if it's connected, all you have to manage is the two following constants:

https://github.com/LeoColomb/Arduino-SRF/blob/d53430e145651778802ebc47b101082e710b421e/examples/SRF08/SRF08.ino#L17-L22

This is where you can manage how the sensor will behave and what data you will receive (range & gain).

> but no sensor reading

No output at all? Could you elaborate?

> I need a 6 meters range

You will never get 6 meters range. I know it's a bit disappointing, but this is the theoretical limit, not the reality. Maybe 5 meters, 5,5 meters if you're lucky.

**Comment by AhUhmm** [comment]
> No output at all? Could you elaborate?

Yes, exactly. The LED behind the sensor blinks only after the setup, and I don't get any sensor readings on the serial monitor after the message stating that a connection has been established.

I also noticed that using your library I have to unplug the Arduino from the USB each time I upload a sketch with some changes int he code, otherwise the I2C communication doesn't work at all. I checked it with [this](https://playground.arduino.cc/Main/I2cScanner) sketch.

> You will never get 6 meters range. I know it's a bit disappointing, but this is the theoretical limit, not the reality. Maybe 5 meters, 5,5 meters if you're lucky.

Really? That's a pity... I chose the SRF08 specifically because according to the [specifications](http://www.robot-electronics.co.uk/htm/srf08tech.html) it is supposed to reach up to that range. 

Anyway, I tried the library specifically because it seemed like the most straightforward way to change those registers, and the constants used in the SRF08 examples are the settings I need for my project!

**Comment by LeoColomb** [comment]
Yep, I2C communication is not really easy with Arduino, don't know why. Maybe this is the case only with SRF08 sensors.
At this point, I can't help you anymore, you already know everything. First try reducing the range at the minimum, change constants, to get at least some readings.

If you find something that can be improved, or just something interesting, feel free to come back here! 😃

**Comment by AhUhmm** [comment]
A quick update. I checked your library also with a SRF10, and I cannot get past the setup message.
With the [SRF example](https://www.arduino.cc/en/Tutorial/SFRRangerReader) that comes with the Wire library I don't have any problems in getting readings from the sensor.

Anyway, would you mind telling me how I could write on the registers to change the Gain and Range?Is it something like this:

```
Wire.beginTransmission(ADDRESS);
Wire.write(byte(0x02);
Wire.write(RANGE);
Wire.endTransmission();
```
This has to be set before the Unit (cm, inch, mS), right?
